const platycerium = [
  {
    name: "コロナリウム",
    water: "多め",
    size: "大きい",
    shape: "ふしぎ",
    price: "普通",
    difficulty: "普通",
    growth: "普通",
    description: "大きく広がる葉と独特な雰囲気が魅力の原種。存在感があり、インテリアの主役になりやすいビカクシダです。",
    image: "images/coronarium.png",
    imageCredit: "みんく 様 (X:@D1yK6)"
  },
  {
    name: "グランデ",
    water: "多め",
    size: "大きい",
    shape: "かっこいい",
    price: "普通",
    difficulty: "普通",
    growth: "普通",
    description: "大きく堂々と育つ姿が魅力の原種。迫力のあるビカクシダを育てたい人に向いています。",
    image: "images/grande.png",
    imageCredit: "未設定"
  },
  {
    name: "ホルタミー",
    water: "多め",
    size: "大きい",
    shape: "ふしぎ",
    price: "高い",
    difficulty: "難しい",
    growth: "遅い",
    description: "個性的な姿と希少性が魅力の原種。栽培難易度は高めですが、コレクション性の高いビカクシダです。",
    image: "images/holttumii.png",
    imageCredit: "未設定"
  },
  {
    name: "リドレイ",
    water: "少なめ",
    size: "小さい",
    shape: "ふしぎ",
    price: "高い",
    difficulty: "難しい",
    growth: "遅い",
    description: "丸みのある貯水葉と個性的なシルエットが人気の原種。小型でも存在感があり、特徴的な姿を楽しめます。",
    image: "images/ridleyi.png",
    imageCredit: "未設定"
  },
  {
    name: "ワリチー",
    water: "多め",
    size: "大きい",
    shape: "ふしぎ",
    price: "高い",
    difficulty: "難しい",
    growth: "遅い",
    description: "ワイルドで独特な雰囲気を持つ原種。育成にはやや慣れが必要ですが、原種らしい魅力を味わえます。",
    image: "images/wallichii.png",
    imageCredit: "鈴木君 様 (X:@DIJd0btaLr7wdM3)"
  },
  {
    name: "ワンダエ",
    water: "多め",
    size: "大きい",
    shape: "かっこいい",
    price: "高い",
    difficulty: "難しい",
    growth: "普通",
    description: "大型で迫力のある姿が魅力の原種。インパクトのある株を育てたい人に向いています。",
    image: "images/wandae.png",
    imageCredit: "かみかぜ 様 (X:@kamikaze_plants)"
  },
  {
    name: "ビフルカツム",
    water: "普通",
    size: "普通",
    shape: "かっこいい",
    price: "安い",
    difficulty: "簡単",
    growth: "早い",
    description: "最もスタンダードな原種のひとつ。流通量が多く、丈夫で育てやすいため、初心者にもおすすめです。",
    image: "images/bifurcatum.png",
    imageCredit: "えにし(X:@enishi18361)"
  },
  {
    name: "ヒリー",
    water: "普通",
    size: "普通",
    shape: "かわいい",
    price: "普通",
    difficulty: "簡単",
    growth: "早い",
    description: "比較的育てやすく、やわらかい雰囲気の葉姿が魅力の原種。ビカクシダ初心者にも扱いやすい種類です。",
    image: "images/hillii.png",
    imageCredit: "未設定"
  },
  {
    name: "スパーバム",
    water: "普通",
    size: "大きい",
    shape: "かっこいい",
    price: "普通",
    difficulty: "普通",
    growth: "普通",
    description: "大きく広がる貯水葉が魅力の原種。迫力があり、壁掛けで育てると存在感が出ます。",
    image: "images/superbum.png",
    imageCredit: "えにし(X:@enishi18361)"
  },
  {
    name: "ベイチー",
    water: "少なめ",
    size: "普通",
    shape: "かっこいい",
    price: "普通",
    difficulty: "普通",
    growth: "普通",
    description: "銀白色の葉が美しい原種。乾燥に比較的強く、シャープでかっこいい印象を楽しめます。",
    image: "images/veitchii.png",
    imageCredit: "えにし(X:@enishi18361)"
  },
  {
    name: "ウィリンキー",
    water: "普通",
    size: "普通",
    shape: "かっこいい",
    price: "普通",
    difficulty: "普通",
    growth: "普通",
    description: "細長く伸びる胞子葉が魅力の原種。スタイリッシュな見た目で、人気の高いビカクシダです。",
    image: "images/willinckii.png",
    imageCredit: "えにし(X:@enishi18361)"
  },
  {
    name: "アンディナム",
    water: "少なめ",
    size: "普通",
    shape: "かっこいい",
    price: "高い",
    difficulty: "難しい",
    growth: "遅い",
    description: "南米系の個性的な原種。流通量が少なく、栽培難易度も高めですが、独自の存在感があります。",
    image: "images/andinum.png",
    imageCredit: "未設定"
  },
  {
    name: "アルシコルネ",
    water: "普通",
    size: "普通",
    shape: "かっこいい",
    price: "普通",
    difficulty: "簡単",
    growth: "早い",
    description: "比較的育てやすく、バランスの良い姿に育ちやすい原種。はじめての原種にも選びやすい種類です。",
    image: "images/alcicorne.png",
    imageCredit: "食べちゃん 様 (X:@tabetyandesu)"
  },
  {
    name: "エレファントティス",
    water: "多め",
    size: "大きい",
    shape: "ふしぎ",
    price: "普通",
    difficulty: "普通",
    growth: "普通",
    description: "幅広で丸みのある葉姿が特徴的な原種。名前の通り、どっしりとした印象を楽しめます。",
    image: "images/elephantotis.png",
    imageCredit: "かずくさ 様 (X:@AKazukusa)"
  },
  {
    name: "エリシー",
    water: "普通",
    size: "小さい",
    shape: "かわいい",
    price: "高い",
    difficulty: "難しい",
    growth: "遅い",
    description: "小型で繊細な雰囲気を持つ原種。かわいらしい姿が魅力ですが、栽培にはやや注意が必要です。",
    image: "images/ellisii.png",
    imageCredit: "未設定"
  },
  {
    name: "ステマリア",
    water: "普通",
    size: "普通",
    shape: "かわいい",
    price: "普通",
    difficulty: "普通",
    growth: "普通",
    description: "やわらかい印象の葉姿が魅力の原種。派手すぎず、落ち着いた雰囲気で育てられます。",
    image: "images/stemaria.png",
    imageCredit: "未設定"
  },
  {
    name: "マダガスカリエンセ",
    water: "多め",
    size: "小さい",
    shape: "ふしぎ",
    price: "高い",
    difficulty: "難しい",
    growth: "遅い",
    description: "網目状の貯水葉が非常に特徴的な原種。独特な造形美があり、コレクション性の高い種類です。",
    image: "images/madagascariense.png",
    imageCredit: "未設定"
  },
  {
    name: "クアドリディコトマム",
    water: "多め",
    size: "小さい",
    shape: "ふしぎ",
    price: "高い",
    difficulty: "難しい",
    growth: "遅い",
    description: "小型で個性的な姿を持つ希少性の高い原種。独特な雰囲気を楽しみたい人向けです。",
    image: "images/quadridichotomum.png",
    imageCredit: "鈴木君 様 (X:@DIJd0btaLr7wdM3)"
  }
];